<div class="gUpMoreOptionsItem"><div class="gUpMoreOptionsName">Duração:</div> {ajax_input permission=$permission value=$arquivo.duracao id="duracao" default="??" display="inline"} s</div>
<div class="gUpMoreOptionsItem"><div class="gUpMoreOptionsName">Tipo do audio:</div> {ajax_input permission=$permission value=$arquivo.tipoDoAudio id="tipoDoAudio" default="" display="inline"}</div>
<div class="gUpMoreOptionsItem"><div class="gUpMoreOptionsName">bpm:</div> {ajax_input permission=$permission value=$arquivo.bpm id="bpm" default="??" display="inline"}</div>
<div class="gUpMoreOptionsItem"><div class="gUpMoreOptionsName">Sample Rate:</div> {ajax_input permission=$permission value=$arquivo.sampleRate id="sampleRate" default="??" display="inline"} hz</div>
<div class="gUpMoreOptionsItem"><div class="gUpMoreOptionsName">Bit Rate:</div> {ajax_input permission=$permission value=$arquivo.bitRate id="bitRate" default="??" display="inline"} bits</div>
<div class="gUpMoreOptionsItem"><div class="gUpMoreOptionsName">Gênero:</div> {ajax_input permission=$permission value=$arquivo.genero id="genero" default="" display="inline"}</div>
<div class="gUpMoreOptionsItem"><div class="gUpMoreOptionsName">Álbum:</div> {ajax_input permission=$permission value=$arquivo.album id="album" default="" display="inline"}</div>
<div class="gUpMoreOptionsItem">Letra:</div>
{ajax_textarea permission=$permission value=$arquivo.letra id="letra" default="" display="block" style="width: 235px; height:125px; border: 1px inset rgb(233, 233, 174);padding: 3px;font-size: 12px; font-family: Arial, Verdana, Helvetica, Lucida, Sans-Serif;background-color: #f1f1f1;margin-bottom: 5px;" wikiParsed=1}<br/>
<div class="gUpMoreOptionsItem">Ficha Técnica:</div>
{ajax_textarea permission=$permission value=$arquivo.fichaTecnica id="fichaTecnica" default="" display="block" style="width: 235px; height:125px; border: 1px inset rgb(233, 233, 174);padding: 3px;font-size: 12px; font-family: Arial, Verdana, Helvetica, Lucida, Sans-Serif;background-color: #f1f1f1;margin-bottom: 5px;" wikiParsed=1}<br/>